### ISSUE TITLE
Does this plugin support webGL？

### ISSUE THREAD

**Issue by WMZL** [needle-mirror/com.unity.live-capture#2]
I have successfully published the exe, but there will be such an error like “To use dlopen, you need to use Emscripten's linking support, see  https://github.com/kripken/emscripten/wiki/Linking” on the webGL platform. May I ask what needs to be modified before it can be used on the WebGL platform?Thank you very much

**Comment by marwie** [comment]
Hello, please ask questions in the official Unity forums or report bugs to Unity directly
